--- 
title: "Introduction to Statistical Computing in Political Science"
author: "Marcy Shieh"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This bookdown book contains materials for PS811."
---

# Introduction {#intro}

This is a one-credit, pass/fail course for first-year PhD students at the Department of Political Science at the University of Wisconsin-Madison. Students will learn how to organize their projects using Git, connect to Github, become R-literate, use R to conduct statistical analyses and create graphics, write their documents in an R Markdown file, create a replicable R Project, and use other computing tools that may help them on their academic journey. Due to COVID-19, the course will be taught virtually during the Fall 2020 semester and recordings of the lectures will be available on Canvas to enrolled students.

The first hour of the course covers everything that students need to know to complete all assignments in the class. The second hour walks through the weekly assignments and provides additional support. To balance out the effects of the virtual environment, I will try to make the class as connected as possible. In addition to regular office hours, we will have a Slack for class questions and discussion. The hope is that each student will be able to get their questions answered as soon as possible.

You may access the [latest draft of the syllabus here](https://github.com/marcyshieh/ps811/blob/master/syllabus/ps811_fall2020_syllabus.pdf).

All course materials are located at the [course GitHub folder](https://github.com/marcyshieh/ps811).

If you have any questions about the materials, please contact me at [mshieh2@wisc.edu](mailto:mshieh2@wisc.edu).
